version: "1"

services:
  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:4.2.16-bionic"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_NAME}
      - MONGO_INITDB_ROOT_PASSwORD=${MONGO_DB_PASSWORD}
    ports:
      - "21017:21017"